# TCL File Generated by Component Editor 15.0
# Sat Apr 16 11:13:10 EDT 2016
# DO NOT MODIFY


# 
# puf "puf" v1.0
#  2016.04.16.11:13:09
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module puf
# 
set_module_property DESCRIPTION ""
set_module_property NAME puf
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME puf
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL puf_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file comparator.vhd VHDL PATH ../hdl/comparator.vhd
add_fileset_file counter.vhd VHDL PATH ../hdl/counter.vhd
add_fileset_file mux.vhd VHDL PATH ../hdl/mux.vhd
add_fileset_file puf.vhd VHDL PATH ../hdl/puf.vhd
add_fileset_file puf_top.vhd VHDL PATH ../hdl/puf_top.vhd TOP_LEVEL_FILE
add_fileset_file ring_oscillator.vhd VHDL PATH ../hdl/ring_oscillator.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point resetn
# 
add_interface resetn reset end
set_interface_property resetn associatedClock clock
set_interface_property resetn synchronousEdges DEASSERT
set_interface_property resetn ENABLED true
set_interface_property resetn EXPORT_OF ""
set_interface_property resetn PORT_NAME_MAP ""
set_interface_property resetn CMSIS_SVD_VARIABLES ""
set_interface_property resetn SVD_ADDRESS_GROUP ""

add_interface_port resetn rstn reset_n Input 1


# 
# connection point puf
# 
add_interface puf avalon end
set_interface_property puf addressUnits WORDS
set_interface_property puf associatedClock clock
set_interface_property puf associatedReset resetn
set_interface_property puf bitsPerSymbol 8
set_interface_property puf burstOnBurstBoundariesOnly false
set_interface_property puf burstcountUnits WORDS
set_interface_property puf explicitAddressSpan 0
set_interface_property puf holdTime 0
set_interface_property puf linewrapBursts false
set_interface_property puf maximumPendingReadTransactions 0
set_interface_property puf maximumPendingWriteTransactions 0
set_interface_property puf readLatency 0
set_interface_property puf readWaitTime 1
set_interface_property puf setupTime 0
set_interface_property puf timingUnits Cycles
set_interface_property puf writeWaitTime 0
set_interface_property puf ENABLED true
set_interface_property puf EXPORT_OF ""
set_interface_property puf PORT_NAME_MAP ""
set_interface_property puf CMSIS_SVD_VARIABLES ""
set_interface_property puf SVD_ADDRESS_GROUP ""

add_interface_port puf avs_address address Input 12
add_interface_port puf avs_write write Input 1
add_interface_port puf avs_writedata writedata Input 32
add_interface_port puf avs_read read Input 1
add_interface_port puf avs_readdata readdata Output 32
set_interface_assignment puf embeddedsw.configuration.isFlash 0
set_interface_assignment puf embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment puf embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment puf embeddedsw.configuration.isPrintableDevice 0

